ALTER VIEW VW_D_EMPRESA

AS

SELECT 0 AS COD_EMPRESA
,'Nao informada' AS NOME
,'Nao informado' AS NOME_FANTASIA


UNION ALL

SELECT	COD_EMPRESA
		,DBO.FN_PASCAL_CASE(NOME) AS NOME
		,DBO.FN_PASCAL_CASE(NOME_FANTASIA) AS NOME_FANTASIA
		FROM ST_EMPRESAS
		

