CREATE PROCEDURE USP_ST_CARGA_VENDEDOR
AS

----------VERIFICAR SCHEMA EXISTENTE----------

IF OBJECT_ID('ST_VENDEDORES') IS NULL
BEGIN

CREATE TABLE ST_VENDEDORES
(
COD_VENDEDOR NUMERIC(15),
NOME VARCHAR(100)
)
END

----------LIMPA STAGE----------

TRUNCATE TABLE ST_VENDEDORES

-------POPULAR STAGE--------

INSERT INTO ST_VENDEDORES(
COD_VENDEDOR,
NOME
)

SELECT VENDEDOR,
NOME
FROM PBS_PROCFIT_DADOS.DBO.VENDEDORES