CREATE PROCEDURE USP_ST_CARGA_PRODUTOS
AS

----------VERIFICAR SCHEMA EXISTENTE----------

IF OBJECT_ID('ST_PRODUTOS') IS NULL

BEGIN

CREATE TABLE ST_PRODUTOS
(
	COD_PRODUTO NUMERIC(15),
	DESCRICAO VARCHAR(100), 
	DESCRICAO_REDUZIDA VARCHAR(60),
	FAMILIA_PRODUTO VARCHAR(80),
	SECAO_PRODUTO VARCHAR(80),
	GRUPO_PRODUTO  VARCHAR(80),
	SUBGRUPO_PRODUTO  VARCHAR(80),
	MARCA  VARCHAR(80)



)

END

----------LIMPA STAGE----------

TRUNCATE TABLE ST_PRODUTOS

-------POPULAR STAGE--------

INSERT INTO ST_PRODUTOS

(
COD_PRODUTO,
DESCRICAO,
DESCRICAO_REDUZIDA,
FAMILIA_PRODUTO,
SECAO_PRODUTO,
GRUPO_PRODUTO,
SUBGRUPO_PRODUTO,
MARCA
)

SELECT	A.PRODUTO,
		A.DESCRICAO, 
		A.DESCRICAO_REDUZIDA,
		B.DESCRICAO AS FAMILIA_PRODUTO,
		C.DESCRICAO AS SECAO_PRODUTO,
		D.DESCRICAO AS GRUPO_PRODUTO,
		E.DESCRICAO AS SUBGRUPO_PRODUTO,
		F.DESCRICAO AS MARCA
FROM PBS_PROCFIT_DADOS.DBO.PRODUTOS A
LEFT JOIN PBS_PROCFIT_DADOS.DBO.FAMILIAS_PRODUTOS		B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO
	 JOIN PBS_PROCFIT_DADOS.DBO.SECOES_PRODUTOS			C ON A.SECAO_PRODUTO = C.SECAO_PRODUTO
	 JOIN PBS_PROCFIT_DADOS.DBO.GRUPOS_PRODUTOS			D ON A.GRUPO_PRODUTO = D.GRUPO_PRODUTO
	 JOIN PBS_PROCFIT_DADOS.DBO.SUBGRUPOS_PRODUTOS		E ON A.SUBGRUPO_PRODUTO = E.SUBGRUPO_PRODUTO
LEFT JOIN PBS_PROCFIT_DADOS.DBO.MARCAS					F ON A.MARCA =		F.MARCA