IF OBJECT_ID('ST_PRODUTOS') IS NULL

BEGIN

CREATE TABLE ST_PRODUTOS
(
	COD_PRODUTO NUMERIC(15),
	DESCRICAO VARCHAR(100), 
	DESCRICAO_REDUZIDA VARCHAR(60),
	FAMILIA_PRODUTO VARCHAR(80),
	SECAO_PRODUTO VARCHAR(80),
	GRUPO_PRODUTO  VARCHAR(80),
	SUBGRUPO_PRODUTO  VARCHAR(80),
	MARCA  VARCHAR(80)



)

END