
ALTER VIEW VW_D_PRODUTOS

AS

SELECT 0 AS COD_PRODUTO
,'Nao informado' AS DESCRICAO
,'Nao informado' AS DESCRICAO_REDUZIDA
,'Nao informado' AS FAMILIA
,'Nao informada' AS SECAO
,'Nao informado' AS GRUPO
,'Nao informado' AS SUBGRUPO
,'Nao informada' AS MARCA

UNION ALL

SELECT 
COD_PRODUTO
,DBO.FN_PASCAL_CASE(DESCRICAO) AS DESCRICAO
,DBO.FN_PASCAL_CASE(DESCRICAO_REDUZIDA) AS DESCRICAO_REDUZIDA
,ISNULL(DBO.FN_PASCAL_CASE(FAMILIA_PRODUTO), 'Nao informada') AS FAMILIA
,DBO.FN_PASCAL_CASE(SECAO_PRODUTO) AS SECAO
,DBO.FN_PASCAL_CASE(GRUPO_PRODUTO) AS GRUPO
,DBO.FN_PASCAL_CASE(SUBGRUPO_PRODUTO) AS SUBGRUPO
,DBO.FN_PASCAL_CASE(MARCA) AS MARCA

FROM PROCFIT_ST.DBO.ST_PRODUTOS

