IF OBJECT_ID('D_CLIENTE') IS NULL

BEGIN
CREATE TABLE D_CLIENTE
(
COD_CLIENTE		NUMERIC (15) PRIMARY KEY
,NOME			VARCHAR(160)
,NOME_FANTASIA  VARCHAR(80)
,CLASSIFICACAO  VARCHAR(160)
,CIDADE			VARCHAR(80)
,ESTADO			VARCHAR(80)
,UF				CHAR(2)


)
END
