IF OBJECT_ID('F_VENDAS') IS NULL

BEGIN


CREATE TABLE F_VENDAS

(
N_DOC NUMERIC (9)
,COD_EMPRESA NUMERIC (15) REFERENCES D_EMPRESA (COD_EMPRESA)  --Consultei a D_EMPRESA para definir o tipo e tamanho
,COD_CLIENTE NUMERIC (15) REFERENCES D_CLIENTE (COD_CLIENTE) --Também consultei a D_CLIENTES para definir
,COD_VENDEDOR NUMERIC (15) REFERENCES D_VENDEDORES (COD_VENDEDOR)  --Também consultei a D_VENDEDORES para definir
,MOVIMENTO DATE
,COD_PRODUTO NUMERIC (15) REFERENCES D_PRODUTO (COD_PRODUTO) --Também consultei a D_PRODUTO para definir
,QUANTIDADE INT
,VENDA_BRUTA MONEY
,DESCONTO_TOTAL MONEY
,VENDA_LIQUIDA MONEY
)

END