
MERGE D_CLIENTE						D
USING PROCFIT_ST.DBO.VW_D_CLIENTE	O ON D.COD_CLIENTE = O.COD_CLIENTE


WHEN MATCHED THEN UPDATE
SET NOME = O.NOME
,NOME_FANTASIA = O.NOME_FANTASIA
,CLASSIFICACAO = O.CLASSIFICACAO_CLIENTE
,CIDADE = O.CIDADE
,ESTADO = O.ESTADO
,UF = O.UF

WHEN NOT MATCHED BY TARGET THEN
			INSERT ( COD_CLIENTE
					,NOME
					,NOME_FANTASIA
					,CLASSIFICACAO
					,CIDADE
					,ESTADO
					,UF)
			VALUES (O.COD_CLIENTE
					,O.NOME
					,O.NOME_FANTASIA
					,O.CLASSIFICACAO_CLIENTE
					,O.CIDADE
					,O.ESTADO
					,O.UF);

