
MERGE D_PRODUTO			D
USING PROCFIT_ST.DBO.VW_D_PRODUTOS	O ON D.COD_PRODUTO = O.COD_PRODUTO


WHEN MATCHED THEN UPDATE
SET
 DESCRICAO            = O.DESCRICAO
,DESCRICAO_REDUZIDA   = O.DESCRICAO_REDUZIDA
,FAMILIA_PRODUTO	  = O.FAMILIA
,SECAO_PRODUTO		  = O.SECAO
,GRUPO_PRODUTO		  = O.GRUPO
,SUBGRUPO_PRODUTO	  = O.SUBGRUPO
,MARCA				  = O.MARCA


WHEN NOT MATCHED BY TARGET THEN
INSERT (
COD_PRODUTO
,DESCRICAO
,DESCRICAO_REDUZIDA
,FAMILIA_PRODUTO
,SECAO_PRODUTO
,GRUPO_PRODUTO
,SUBGRUPO_PRODUTO
,MARCA

)

VALUES(
COD_PRODUTO
,O.DESCRICAO
,O.DESCRICAO_REDUZIDA
,O.FAMILIA
,O.SECAO
,O.GRUPO
,O.SUBGRUPO
,O.MARCA

);


