IF OBJECT_ID('ST_VENDAS') IS NULL
BEGIN

CREATE TABLE ST_VENDAS(
N_DOC NUMERIC (15),
COD_EMPRESA NUMERIC (15),
COD_CLIENTE NUMERIC (15),
COD_VENDEDOR NUMERIC (15),
MOVIMENTO DATE, 
COD_PRODUTO NUMERIC (15),
QUANTIDADE INT, 
VENDA_BRUTA MONEY, 
DESCONTO_TOTAL MONEY,
VENDA_LIQUIDA MONEY



)
END