SELECT  A.ENTIDADE, 
		A.NOME, 
		A.NOME_FANTASIA, 
		B.DESCRICAO AS NOME_CLASSIFICACAO, 
		C.CIDADE, 
		C.ESTADO AS UF, 
		D.NOME AS ESTADO
FROM ENTIDADES A
LEFT JOIN CLASSIFICACOES_CLIENTES B ON A.CLASSIFICACAO_CLIENTE  = B.CLASSIFICACAO_CLIENTE
LEFT JOIN ENDERECOS C ON A.ENTIDADE								= C.ENTIDADE
LEFT JOIN ESTADOS D ON C.ESTADO									= D.ESTADO