TRUNCATE TABLE ST_CLIENTES

INSERT INTO ST_CLIENTES
(
COD_CLIENTE, 
NOME, 
NOME_FANTASIA,
COD_CLASSIFICACAO
)

SELECT A.ENTIDADE, A.NOME, A.NOME_FANTASIA, A.CLASSIFICACAO_CLIENTE
FROM PBS_PROCFIT_DADOS.DBO.ENTIDADES A 

SELECT * FROM ST_CLIENTES
