/*
TABELA DE CLASSIFICACOES_CLIENTE

CLASSIFICACAO_CLIENTE,
DESCRICAO
*/

IF OBJECT_ID('ST_CLIENTES_CLASSIFICACOES') IS NULL

BEGIN

CREATE TABLE ST_CLIENTES_CLASSIFICACOES
(
COD_CLASSIFICACAO			NUMERIC(15), 
DESCRICAO					VARCHAR(100)
)
END