TRUNCATE TABLE ST_CLIENTES_CLASSIFICACOES

INSERT INTO ST_CLIENTES_CLASSIFICACOES
(
COD_CLASSIFICACAO, 
DESCRICAO
)

SELECT CLASSIFICACAO_CLIENTE, 
DESCRICAO
FROM PBS_PROCFIT_DADOS.DBO.CLASSIFICACOES_CLIENTES

SELECT * FROM ST_CLIENTES_CLASSIFICACOES


