ALTER VIEW VW_D_CLIENTE


AS

--Criando valores default

SELECT 0 AS COD_CLIENTE
,'Nao informado' AS NOME
,'Nao informado' AS NOME_FANTASIA
,'Nao informado' AS CLASSIFICACAO_CLIENTE
,'Nao informada' AS CIDADE
,'Nao informado' AS ESTADO
,'ND' AS UF

UNION ALL


SELECT	A.COD_CLIENTE
		,A.NOME
		,A.NOME_FANTASIA
		,ISNULL(DBO.FN_PASCAL_CASE(B.DESCRICAO), 'Nao informado') AS CLASSIFICACAO_CLIENTE
		,ISNULL(DBO.FN_PASCAL_CASE(C.CIDADE), 'Nao informado') AS CIDADE
		,ISNULL(DBO.FN_PASCAL_CASE(D.CIDADE), 'Nao informado') AS ESTADO
		,ISNULL(C.UF, 'ND') AS UF
FROM ST_CLIENTES						A 
LEFT JOIN ST_CLIENTES_CLASSIFICACOES	B ON A.COD_CLASSIFICACAO =	B.COD_CLASSIFICACAO
LEFT JOIN ST_CLIENTES_ENDEREÇOS			C ON A.COD_CLIENTE =		C.ENTIDADE
LEFT JOIN ST_CLIENTES_ESTADOS			D ON C.UF =					D.UF


